logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: cleanarchmattec

mattec:
  client:
    address:
#      url: http://localhost:8082/addresses
      url: https://viacep.com.br/ws/

server:
  port: 8081